### ISSUE TITLE
Quiz is submitting even if Contact details are set to Required? in IE

### ISSUE THREAD

**Issue by gamekid88** [fpcorso/quiz_master_next#270]
Sometimes when a user submits a quiz with contact details set to Required? and the user did not put anything into the contact details fields the quiz is still allowed to be submitted. This so far has been only proven in Internet Explorer. So far Chrome and Firefox are working correctly. 

Also, part of the issue was a conflict with the plugin Easy WP STMP in the beginning. Not sure if it is an issue right now.

**Comment by fpcorso** [comment]
This bug shows in IE due to how IE handles undefined JavaScript variables. Our variable on qmn_quiz_id is defined inside the timer function here:
https://github.com/fpcorso/quiz_master_next/blob/master/php/qmn_quiz.php#L1287

However, we use that variable to check the status of the timer in the validation file. So, if the timer is not turned on, IE throws an error.

To fix this, simply move the qmn_quiz_id variable to the main shortcode function. Preferably in the JS global variables section found here:
https://github.com/fpcorso/quiz_master_next/blob/master/php/qmn_quiz.php#L222
