### ISSUE TITLE
cursor not getting displayed after some test

### ISSUE THREAD

**Issue by artemis15** [fpcorso/quiz_master_next#411]
Hi,

Thanks for the great plugin. It works like a charm. From past some days, I'm facing some issues.

After giving some quizes, cursor was not getting displayed in the input boxes. This has been reported to me from a large group of users. 

Attaching screenshot for the same.

--
Thanks
![test](https://cloud.githubusercontent.com/assets/8123664/14759798/417f4eee-094d-11e6-8d05-ac0c8805f79a.jpg)

**Comment by fpcorso** [comment]
Hey @artemis15 . Thank you for reaching out to us. Have you already created a support ticket for this?

If not, would you be able to perform a plugin conflict check? This process will check to see if there is a plugin that you have installed that may not be compatible with the plugin that you are trying to use. To do this, first de-activate all other plugins besides Quiz And Survey Master. Now, check to see if it is working correctly. If this fixed the problem, this suggests that it is a plugin conflict issue. 

To discover which plugin may contain the conflict, activate one plugin and then check if the plugin you are setting up still works. If it no longer works again, the plugin you just re-activate is the plugin conflict. If not, continue to activate the plugins one by one and check to see if the problem arises again. If you do find a plugin conflict, please let me know which plugin and which version of the plugin that you are using.

Also, can you provide a link to your quiz after doing the plugin check so that we debug the frontend code?
