### ISSUE TITLE
Page counter

### ISSUE THREAD

**Issue by Cocoslocos** [fpcorso/quiz_master_next#680]
Hello!

I saw that the Plugin has the capability of display which question number out of total number of questions you’re currently answering, but I haven’t been able to find where to enable this however. Has someone been able to place it? Thank you!

**Comment by fpcorso** [comment]
Hey @Cocoslocos 

This plugin does not currently have a feature to display which number the quiz taker is answering. The plugin does have a progress bar which can be found near the top of the "Options" tab.

**Comment by Cocoslocos** [comment]
Hello @fpcorso ^^

I saw it :D but when I put more than 0 in _How many questions per page would you like? (Leave 0 for all questions on one page)_, the progress bar doesn't appear. It's a bug from me?

Thank you so much ♥

**Comment by fpcorso** [comment]
Hey @Cocoslocos 

Is there are reason you are using "How many questions per page would you like?" instead of creating pages on the "Questions" tab? The progress bar is a new feature and only currently works with the main questions/pages system and not the "How many questions per page would you like?" option.

I plan on making it compatible with that option but I do not have a timeframe for when that will be available.
